# Generated by Django 5.0.9 on 2025-10-14 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'Usuário Criado'), ('USER_UPDATED', 'Usuário Atualizado'), ('USER_DELETED', 'Usuário Deletado'), ('USER_ACTIVATED', 'Usuário Ativado'), ('USER_DEACTIVATED', 'Usuário Desativado'), ('USER_PASSWORD_CHANGED', 'Senha Alterada'), ('USER_LOGIN', 'Login Realizado'), ('USER_LOGOUT', 'Logout Realizado'), ('USER_LOGIN_FAILED', 'Login Falhado'), ('GROUP_CREATED', 'Grupo Criado'), ('GROUP_UPDATED', 'Grupo Atualizado'), ('GROUP_DELETED', 'Grupo Deletado'), ('GROUP_USER_ADDED', 'Usuário Adicionado ao Grupo'), ('GROUP_USER_REMOVED', 'Usuário Removido do Grupo'), ('GROUP_PERMISSION_ADDED', 'Permissão Adicionada ao Grupo'), ('GROUP_PERMISSION_REMOVED', 'Permissão Removida do Grupo'), ('PERMISSION_GRANTED', 'Permissão Concedida'), ('PERMISSION_REVOKED', 'Permissão Revogada'), ('ROLE_CHANGED', 'Papel/Função Alterada'), ('SYSTEM_ACCESS', 'Acesso ao Sistema'), ('DATA_EXPORT', 'Dados Exportados'), ('SETTINGS_CHANGED', 'Configurações Alteradas'), ('CUSTOM_ACTION', 'Ação Customizada')], max_length=50, verbose_name='Ação')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Representação do Objeto')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dados das alterações realizadas', verbose_name='Alterações')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Chave da Sessão')),
                ('success', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Dados adicionais específicos da ação', verbose_name='Dados Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_syste_timesta_9aa2de_idx'), models.Index(fields=['user', 'timestamp'], name='audit_syste_user_id_272d6e_idx'), models.Index(fields=['action', 'timestamp'], name='audit_syste_action_4f3775_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_syste_content_ad8ecd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('action', models.CharField(max_length=50, verbose_name='Ação')),
                ('count', models.IntegerField(default=0, verbose_name='Contador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumo de Auditoria',
                'verbose_name_plural': 'Resumos de Auditoria',
                'unique_together': {('date', 'user', 'action')},
            },
        ),
    ]
