# Generated by Django 5.0.9 on 2025-10-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='default_from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Padrão do Sistema'),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='email_backend',
            field=models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP Backend (Padrão)'), ('django.core.mail.backends.console.EmailBackend', 'Console Backend (Desenvolvimento)'), ('django.core.mail.backends.filebased.EmailBackend', 'File Backend (Arquivo)'), ('django.core.mail.backends.locmem.EmailBackend', 'Memory Backend (Memória)'), ('django.core.mail.backends.dummy.EmailBackend', 'Dummy Backend (Teste)')], default='django.core.mail.backends.smtp.EmailBackend', max_length=255, verbose_name='Backend de E-mail'),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativado, o sistema usará estas configurações para envio de e-mails', verbose_name='Ativar Configurações'),
        ),
    ]
