# Generated by Django 5.0.9 on 2025-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_smtpsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpsettings',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='smtpsettings',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='smtpsettings',
            name='smtp_username',
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='email',
            field=models.EmailField(default='noreply@webreceptivo.com', help_text='E-mail usado para autenticação, remetente e todas as funções do sistema', max_length=254, verbose_name='E-mail SMTP'),
        ),
    ]
