# Generated by Django 5.0.9 on 2025-10-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL para a imagem do perfil do usuário', null=True, verbose_name='URL da Foto do Perfil'),
        ),
    ]
