# Generated by Django 5.0.9 on 2025-10-12 21:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_change_avatar_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Formatos aceitos: JPG, PNG, GIF. Tamanho máximo: 12MB.', null=True, upload_to=accounts.models.user_avatar_path, validators=[accounts.models.validate_avatar_size], verbose_name='Foto do Perfil'),
        ),
    ]
