# Generated by Django 5.2.7 on 2025-12-31 17:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMeiaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Meia Entrada',
                'verbose_name_plural': 'Tipos de Meia Entrada',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_inteira', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Inteira')),
                ('valor_meia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Meia Entrada')),
                ('valor_infantil', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Infantil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='servicos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField(verbose_name='Data do Serviço')),
                ('qtd_inteira', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtd Inteira')),
                ('qtd_meia', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtd Meia Entrada')),
                ('qtd_infantil', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtd Infantil')),
                ('valor_unit_inteira', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unit. Inteira')),
                ('valor_unit_meia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unit. Meia')),
                ('valor_unit_infantil', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unit. Infantil')),
                ('obs_publica', models.TextField(blank=True, help_text='Visível na OS e para o cliente', verbose_name='Observações Públicas')),
                ('obs_privada', models.TextField(blank=True, help_text='Uso interno, não aparece na OS', verbose_name='Observações Privadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.categoria', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.subcategoria', verbose_name='Serviço')),
                ('tipo_meia_entrada', models.ForeignKey(blank=True, help_text='Obrigatório quando houver quantidade de meia entrada', null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.tipomeiaentrada', verbose_name='Tipo de Meia Entrada')),
            ],
            options={
                'verbose_name': 'Lançamento de Serviço',
                'verbose_name_plural': 'Lançamentos de Serviços',
                'ordering': ['-data_servico', '-criado_em'],
            },
        ),
    ]
