# Generated by Django 5.2.7 on 2025-12-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoservico',
            name='idades_criancas',
            field=models.CharField(blank=True, help_text='Informe as idades separadas por vírgula. Ex: 3, 5, 8', max_length=200, verbose_name='Idades das Crianças'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='aceita_meia_entrada',
            field=models.BooleanField(default=True, help_text='Define se este serviço aceita meia entrada', verbose_name='Aceita Meia Entrada'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='regras_meia_entrada',
            field=models.TextField(blank=True, help_text='Ex: EST. DE 9 A 16 ANOS COM RG, EST. COM CARTEIRINHA, PROF BR, IDOSO, etc.', verbose_name='Regras de Meia Entrada'),
        ),
    ]
