# Generated by Django 5.2.7 on 2025-12-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_lancamentoservico_idades_criancas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoservico',
            name='tipos_meia_entrada',
            field=models.TextField(blank=True, help_text='Informe um tipo por linha quando houver múltiplas meias entradas. Ex:\nEstudante\nIdoso', verbose_name='Tipos de Meia Entrada'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='idade_isencao_max',
            field=models.PositiveIntegerField(default=0, help_text='Idade máxima para isenção (ex: 6). Use 0 se não houver isenção', verbose_name='Idade Máxima Isenção'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='idade_isencao_min',
            field=models.PositiveIntegerField(default=0, help_text='Idade mínima para isenção (ex: 0)', verbose_name='Idade Mínima Isenção'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='texto_isencao',
            field=models.CharField(blank=True, help_text='Ex: CRIANÇA DE 0 A 6 ANOS', max_length=200, verbose_name='Texto da Isenção'),
        ),
    ]
