# Generated by Django 5.2.7 on 2025-12-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_lancamentoservico_tipos_meia_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentoservico',
            name='tipo_meia_entrada',
        ),
        migrations.AlterField(
            model_name='lancamentoservico',
            name='idades_criancas',
            field=models.JSONField(blank=True, default=list, help_text='Lista com as idades de cada criança. Ex: [3, 5, 8]', verbose_name='Idades das Crianças'),
        ),
        migrations.RemoveField(
            model_name='lancamentoservico',
            name='tipos_meia_entrada',
        ),
        migrations.AddField(
            model_name='lancamentoservico',
            name='tipos_meia_entrada',
            field=models.ManyToManyField(blank=True, help_text='Selecione os tipos de meia entrada aplicáveis', related_name='lancamentos', to='servicos.tipomeiaentrada', verbose_name='Tipos de Meia Entrada'),
        ),
    ]
