# Generated by Django 5.2.7 on 2025-12-31 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_remove_lancamentoservico_tipo_meia_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoservico',
            name='tipo_meia_entrada',
            field=models.ForeignKey(blank=True, help_text='Obrigatório quando houver quantidade de meia entrada', null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.tipomeiaentrada', verbose_name='Tipo de Meia Entrada'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='idade_minima',
            field=models.PositiveIntegerField(default=0, help_text='Idade mínima permitida para este serviço (ex: 6). Use 0 se não houver restrição', verbose_name='Idade Mínima'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='tem_idade_minima',
            field=models.BooleanField(default=False, help_text='Define se este serviço exige idade mínima', verbose_name='Possui Idade Mínima'),
        ),
        migrations.AlterField(
            model_name='lancamentoservico',
            name='idades_criancas',
            field=models.CharField(blank=True, help_text='Informe as idades separadas por vírgula. Ex: 3, 5, 8', max_length=200, verbose_name='Idades das Crianças'),
        ),
        migrations.RemoveField(
            model_name='lancamentoservico',
            name='tipos_meia_entrada',
        ),
        migrations.AddField(
            model_name='lancamentoservico',
            name='tipos_meia_entrada',
            field=models.TextField(blank=True, help_text='Informe um tipo por linha quando houver múltiplas meias entradas. Ex:\nEstudante\nIdoso', verbose_name='Tipos de Meia Entrada'),
        ),
    ]
