# Generated by Django 5.2.7 on 2025-12-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_adicionar_idade_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='permite_infantil',
            field=models.BooleanField(default=True, help_text='Define se este serviço possui categoria infantil', verbose_name='Permite Infantil'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='possui_isencao',
            field=models.BooleanField(default=False, help_text='Define se este serviço possui isenção por faixa etária', verbose_name='Possui Isenção por Idade'),
        ),
    ]
