# Generated by Django 5.2.7 on 2025-12-31 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_adicionar_flags_condicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='idade_maxima_infantil',
            field=models.PositiveIntegerField(default=17, help_text='Idade máxima para categoria infantil (ex: 12). Máximo 17 anos.', validators=[django.core.validators.MaxValueValidator(17)], verbose_name='Idade Máxima Infantil'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='idade_minima_infantil',
            field=models.PositiveIntegerField(default=0, help_text='Idade mínima para categoria infantil (ex: 0). Máximo 17 anos.', validators=[django.core.validators.MaxValueValidator(17)], verbose_name='Idade Mínima Infantil'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='idade_isencao_max',
            field=models.PositiveIntegerField(default=0, help_text='Idade máxima para isenção (ex: 6). Máximo 17 anos. Use 0 se não houver isenção', validators=[django.core.validators.MaxValueValidator(17)], verbose_name='Idade Máxima Isenção'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='idade_isencao_min',
            field=models.PositiveIntegerField(default=0, help_text='Idade mínima para isenção (ex: 0). Máximo 17 anos.', validators=[django.core.validators.MaxValueValidator(17)], verbose_name='Idade Mínima Isenção'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='idade_minima',
            field=models.PositiveIntegerField(default=0, help_text='Idade mínima permitida para este serviço (ex: 6). Máximo 17 anos. Use 0 se não houver restrição', validators=[django.core.validators.MaxValueValidator(17)], verbose_name='Idade Mínima'),
        ),
    ]
