# Generated by Django 5.2.7 on 2026-01-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_adicionar_ordem_servico_transfer_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='servicos.cliente', verbose_name='Cliente'),
        ),
    ]
