# Generated by Django 5.2.7 on 2026-01-01 03:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_alter_ordemservico_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoservico',
            name='valor_transfer_ida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total dos transfers de ida', max_digits=10, verbose_name='Valor Transfer Ida'),
        ),
        migrations.AddField(
            model_name='lancamentoservico',
            name='valor_transfer_volta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total dos transfers de volta', max_digits=10, verbose_name='Valor Transfer Volta'),
        ),
    ]
