# Generated by Django 5.0.9 on 2026-01-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_add_transfer_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferos',
            name='lancamento_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_vinculados', to='servicos.lancamentoservico', verbose_name='Lançamento de Serviço'),
        ),
    ]
