# Generated by Django 5.2.7 on 2026-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_transferos_lancamento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='clientes',
            field=models.CharField(blank=True, help_text='Nome(s) do(s) cliente(s) desta OS', max_length=255, verbose_name='Clientes'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='hospedagem',
            field=models.CharField(blank=True, help_text='Informação de hospedagem', max_length=255, verbose_name='Hospedagem'),
        ),
    ]
