# Generated by Django 5.2.7 on 2026-01-16 16:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0012_ordemservico_clientes_ordemservico_hospedagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='servicos.ordemservico', verbose_name='Ordem de Serviço')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='servicos.transfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer vinculado à OS',
                'verbose_name_plural': 'Transfers vinculados à OS',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='TransferOS',
        ),
    ]
