# Generated by Django 5.2.7 on 2026-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0013_transferordemservico_delete_transferos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferordemservico',
            name='nome_personalizado',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Personalizado'),
        ),
    ]
