# Generated by Django 5.2.7 on 2026-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0014_transferordemservico_nome_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferordemservico',
            name='data_transfer',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Transfer'),
        ),
    ]
